name: CI/CD

on:
  push:
    branches: [dev2]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USER_NAME : ${{ secrets.USERNAME  }}
            DB_CONNECTION_STRING : ${{ secrets.DB_CONNECTION_STRING }}
            SESSION_SECRET : ${{ secrets.SESSION_SECRET }}
            PORT : ${{ secrets.PORT }}
      
        run: |
          echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
          ssh -o StrictHostKeyChecking=no -i private_key ${USER_NAME}@${HOSTNAME} '
          
            rm -rf Chat-App &&
            sudo docker ps -q -a --filter ancestor="chat-app" | xargs -r sudo docker rm -f &&
            sudo docker system prune -a -f &&
            git clone git@github.com:jhassan12/Chat-App.git &&
            cd Chat-App &&
            sudo docker build -t chat-app . &&
            sudo docker run -d -e NODE_ENV=production \
            -e CONNECTION_STRING=${DB_CONNECTION_STRING} \
            -e SESSION_SECRET=${SESSION_SECRET} \
            -e PORT=${PORT} \
            -p ${PORT}:${PORT} chat-app
          '
          
