name: CI/CD

on:
  push:
    branches: [dev2]

jobs:
  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v2 
      - name: Deploy in EC2
        env:
            PRIVATE_KEY: ${{ secrets.AWS_PRIVATE_KEY  }}
            HOSTNAME : ${{ secrets.HOSTNAME  }}
            USERNAME : ${{ secrets.USERNAME  }}
            CONNECTION_STRING : ${{ secrets.DB_CONNECTION_STRING }}
            SESSION_SECRET : ${{ secrets.SESSION_SECRET }}
            PORT : ${{ secrets.PORT }}
      
        run: |
            echo "$PRIVATE_KEY" > private_key && chmod 600 private_key
            ssh -o StrictHostKeyChecking=no -i private_key ${USERNAME}@${HOSTNAME} '
          
            rm -rf Chat-App &&
            git clone -b dev2 git@github.com:jhassan12/Chat-App.git &&
            cd Chat-App &&
            cp ../.env .
            npm install &&
            node app.js
            '
          
          
